server:
  # 端口
  port: 3000

spring:
  # mysql数据库
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbm?characterEncoding=UTF-8&useUnicode=true
    username: root
    password: "000000"
  # 页面热加载
  thymeleaf:
    cache: false
